[profile.default]
src = "forge-tests"
out = "out"
libs = ["node_modules"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=node_modules/forge-std/"
]
solc_version = "0.6.12"
evm_version = "istanbul"
via_ir = false
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
mainnet = "${ETHEREUM_RPC_URL}"
